### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by colesnicov** [cipperly/ImAnim#9]
Can't build on Ubuntu 24.04

```
17:15:41 **** Incremental Build of configuration Debug for project Calendar ****
make -j16 all 
Building file: ../submodules/ImAnim/src/AbstractAnimation.cpp
Invoking: GCC C++ Compiler
g++ -std=c++23 -DGLFW_INCLUDE_ES2=1 -DIMGUI_IMPL_OPENGL_ES2=1 -DIMGUI_DEFINE_MATH_OPERATORS=1 -DSOIL_NO_X11=1 -I"/home/denis/Odey_imgui/Calendar/include" -I"/home/denis/Odey_imgui/Calendar/submodules/imgui" -I"/home/denis/Odey_imgui/Calendar/submodules/libodey_logger/include" -I"/home/denis/Odey_imgui/Calendar/submodules/libodey_configs/include" -I"/home/denis/Odey_imgui/Calendar/submodules/libodey_i10n/include" -I"/home/denis/Odey_imgui/Calendar/submodules/jsonxx" -I"/home/denis/Odey_imgui/Calendar/submodules/libodey_path/include" -I"/home/denis/Odey_imgui/Calendar/submodules/assetManager/include" -I"/home/denis/Odey_imgui/Calendar/submodules/SOIL2/src/SOIL2" -I"/home/denis/Odey_imgui/Calendar/submodules/ImAnim/src" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"submodules/ImAnim/src/AbstractAnimation.d" -MT"submodules/ImAnim/src/AbstractAnimation.o" -o "submodules/ImAnim/src/AbstractAnimation.o" "../submodules/ImAnim/src/AbstractAnimation.cpp"
../submodules/ImAnim/src/AbstractAnimation.cpp: In member function ‘void imanim::AbstractAnimation::start()’:
../submodules/ImAnim/src/AbstractAnimation.cpp:52:59: error: no match for ‘operator=’ (operand types are ‘std::chrono::_V2::steady_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} and ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’})
   52 |     m_startTime = std::chrono::high_resolution_clock::now();
      |                                                           ^
In file included from /usr/include/c++/14/chrono:41,
                 from ../submodules/ImAnim/src/AbstractAnimation.h:4,
                 from ../submodules/ImAnim/src/AbstractAnimation.cpp:1:
/usr/include/c++/14/bits/chrono.h:922:13: note: candidate: ‘constexpr std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >::operator=(const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&)’
  922 |       class time_point
      |             ^~~~~~~~~~
/usr/include/c++/14/bits/chrono.h:922:13: note:   no known conversion for argument 1 from ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} to ‘const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&’
/usr/include/c++/14/bits/chrono.h:922:13: note: candidate: ‘constexpr std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >::operator=(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&&)’
/usr/include/c++/14/bits/chrono.h:922:13: note:   no known conversion for argument 1 from ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} to ‘std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&&’
../submodules/ImAnim/src/AbstractAnimation.cpp: In member function ‘virtual void imanim::AbstractAnimation::update()’:
../submodules/ImAnim/src/AbstractAnimation.cpp:82:51: error: no match for ‘operator-’ (operand types are ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} and ‘std::chrono::_V2::steady_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’})
   82 |         std::chrono::high_resolution_clock::now() - m_startTime;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~
      |                                                |    |
      |                                                |    time_point<std::chrono::_V2::steady_clock,[...]>
      |                                                time_point<std::chrono::_V2::system_clock,[...]>
In file included from /usr/include/c++/14/string:48,
                 from /usr/include/c++/14/bits/locale_classes.h:40,
                 from /usr/include/c++/14/bits/ios_base.h:41,
                 from /usr/include/c++/14/ios:44,
                 from /usr/include/c++/14/istream:40,
                 from /usr/include/c++/14/sstream:40,
                 from /usr/include/c++/14/chrono:45:
/usr/include/c++/14/bits/stl_iterator.h:618:5: note: candidate: ‘template<class _IteratorL, class _IteratorR> constexpr decltype ((__y.base() - __x.base())) std::operator-(const reverse_iterator<_IteratorL>&, const reverse_iterator<_IteratorR>&)’
  618 |     operator-(const reverse_iterator<_IteratorL>& __x,
      |     ^~~~~~~~
/usr/include/c++/14/bits/stl_iterator.h:618:5: note:   template argument deduction/substitution failed:
../submodules/ImAnim/src/AbstractAnimation.cpp:82:53: note:   ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} is not derived from ‘const std::reverse_iterator<_IteratorL>’
   82 |         std::chrono::high_resolution_clock::now() - m_startTime;
      |                                                     ^~~~~~~~~~~
/usr/include/c++/14/bits/stl_iterator.h:1790:5: note: candidate: ‘template<class _IteratorL, class _IteratorR> constexpr decltype ((__x.base() - __y.base())) std::operator-(const move_iterator<_IteratorL>&, const move_iterator<_IteratorR>&)’
 1790 |     operator-(const move_iterator<_IteratorL>& __x,
      |     ^~~~~~~~
/usr/include/c++/14/bits/stl_iterator.h:1790:5: note:   template argument deduction/substitution failed:
../submodules/ImAnim/src/AbstractAnimation.cpp:82:53: note:   ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} is not derived from ‘const std::move_iterator<_IteratorL>’
   82 |         std::chrono::high_resolution_clock::now() - m_startTime;
      |                                                     ^~~~~~~~~~~
/usr/include/c++/14/bits/chrono.h:710:7: note: candidate: ‘template<class _Rep1, class _Period1, class _Rep2, class _Period2> constexpr typename std::common_type<std::chrono::duration<_Rep1, _Period1>, std::chrono::duration<_Rep2, _Period2> >::type std::chrono::operator-(const duration<_Rep1, _Period1>&, const duration<_Rep2, _Period2>&)’
  710 |       operator-(const duration<_Rep1, _Period1>& __lhs,
      |       ^~~~~~~~
/usr/include/c++/14/bits/chrono.h:710:7: note:   template argument deduction/substitution failed:
../submodules/ImAnim/src/AbstractAnimation.cpp:82:53: note:   ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} is not derived from ‘const std::chrono::duration<_Rep1, _Period1>’
   82 |         std::chrono::high_resolution_clock::now() - m_startTime;
      |                                                     ^~~~~~~~~~~
/usr/include/c++/14/bits/chrono.h:1129:7: note: candidate: ‘template<class _Clock, class _Dur1, class _Rep2, class _Period2> constexpr std::chrono::time_point<_Clock, typename std::common_type<_Dur1, std::chrono::duration<_Rep2, _Period2> >::type> std::chrono::operator-(const time_point<_Clock, _Duration1>&, const duration<_Rep2, _Period2>&)’
 1129 |       operator-(const time_point<_Clock, _Dur1>& __lhs,
      |       ^~~~~~~~
/usr/include/c++/14/bits/chrono.h:1129:7: note:   template argument deduction/substitution failed:
../submodules/ImAnim/src/AbstractAnimation.cpp:82:53: note:   ‘std::chrono::_V2::steady_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} is not derived from ‘const std::chrono::duration<_Rep2, _Period2>’
   82 |         std::chrono::high_resolution_clock::now() - m_startTime;
      |                                                     ^~~~~~~~~~~
/usr/include/c++/14/bits/chrono.h:1141:7: note: candidate: ‘template<class _Clock, class _Dur1, class _Dur2> constexpr typename std::common_type<_Duration1, _Duration2>::type std::chrono::operator-(const time_point<_Clock, _Duration1>&, const time_point<_Clock, _Duration2>&)’
 1141 |       operator-(const time_point<_Clock, _Dur1>& __lhs,
      |       ^~~~~~~~
/usr/include/c++/14/bits/chrono.h:1141:7: note:   template argument deduction/substitution failed:
../submodules/ImAnim/src/AbstractAnimation.cpp:82:53: note:   deduced conflicting types for parameter ‘_Clock’ (‘std::chrono::_V2::system_clock’ and ‘std::chrono::_V2::steady_clock’)
   82 |         std::chrono::high_resolution_clock::now() - m_startTime;
      |                                                     ^~~~~~~~~~~
../submodules/ImAnim/src/AbstractAnimation.cpp:98:63: error: no match for ‘operator=’ (operand types are ‘std::chrono::_V2::steady_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} and ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’})
   98 |         m_startTime = std::chrono::high_resolution_clock::now();
      |                                                               ^
/usr/include/c++/14/bits/chrono.h:922:13: note: candidate: ‘constexpr std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >::operator=(const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&)’
  922 |       class time_point
      |             ^~~~~~~~~~
/usr/include/c++/14/bits/chrono.h:922:13: note:   no known conversion for argument 1 from ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} to ‘const std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&’
/usr/include/c++/14/bits/chrono.h:922:13: note: candidate: ‘constexpr std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >& std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >::operator=(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&&)’
/usr/include/c++/14/bits/chrono.h:922:13: note:   no known conversion for argument 1 from ‘std::chrono::_V2::system_clock::time_point’ {aka ‘std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >’} to ‘std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1, 1000000000> > >&&’
make: *** [submodules/ImAnim/src/subdir.mk:47: submodules/ImAnim/src/AbstractAnimation.o] Chyba 1
"make -j16 all" terminated with exit code 2. Build might be incomplete.

17:15:42 Build Failed. 4 errors, 0 warnings. (took 1s.226ms)
```
